name: CI

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.10"

      - name: Install pipenv and project dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --pre

      - name: Run code linter and formatter
        run: |
          make ci
