name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: github.ref != 'refs/heads/main' && github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot PR merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'

      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install Python dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run code linter and formatter
        run: |
          make ci
